name: FastAPI CI with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Build Docker Image
      run: docker build -t fastapi-cicd-app .

    - name: Run container and test health
      run: |
        docker run -d -p 8000:8000 --name test-app fastapi-cicd-app
        sleep 5
        curl --fail http://localhost:8000 || (docker logs test-app && exit 1)
        docker stop test-app